### ISSUE TITLE
how can i only read the last heart rate and save to txt?

### ISSUE THREAD

**Issue by inpanic** [satcar77/miband4#12]
how can i read the live heart rate and save it to txt without the menu and the other stuff?
with cron job
thx ^^

**Comment by satcar77** [comment]
The menu is only for the demo. Check this function:
https://github.com/satcar77/miband4/blob/0935d0d85e8fefbd909e7c97a2e3023342e3f08d/miband4_console.py#L120
Instead of passing a callback function to simply print the data, pass a function to log the data into a text file in `band.start_heart_rate_realtime(heart_measure_callback=heart_logger)`
